todo_list/config/routes.rb
Rails.application.routes.draw do


  resources :tasks do
    get :completed
  end

  root 'tasks#index'










end

todo_list/app/models/task.rb
class Task < ActiveRecord::Base
end

todo_list/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

todo_list/app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(description: params[:task][:description], completed: false)
    redirect_to tasks_path
  end

  def completed
    task = Task.find(params[:task_id])
    task.update_attributes(completed: true)
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
    # @task.update_attributes(description: params[:task][:description])
  end

  def update
    task=Task.find(params[:id])
    task.update_attributes(description: params[:task][:description])
    redirect_to tasks_path
  end

  def destroy
    task=Task.find(params[:id])
    task.destroy
    redirect_to tasks_path
  end

end

todo_list/app/helpers/application_helper.rb
module ApplicationHelper
end

todo_list/app/helpers/lists_helper.rb
module ListsHelper
end

todo_list/app/helpers/tasks_helper.rb
module TasksHelper
end

todo_list/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

todo_list/app/views/tasks/_form.html.erb
<%= form_for @task do |f| %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

todo_list/app/views/tasks/index.html.erb
<h1> Hello, we're Gumby TD. And we're here to organize your life. </h1>
<br><br>


<a href="/tasks/new">Add a new task</a>


<br><br>
<h2> Your Gumby List </h2>
  <table>
    <tr>
      <td>Description</td>
      <td>Completed?</td>
    </tr>

    <% @tasks.each do |task| %>
    <tr>
      <td>  <%= task.description %></td>
      <td>  <%= task.completed %></td>
      <td>  <%= link_to 'Edit',  edit_task_url(task) %></td>
      <td>  <%= link_to 'Complete task',  task_completed_url(task) %></td>
      <td>  <%= link_to 'Delete',  task_url(task), method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
    <% end %>

  </table>

todo_list/app/views/tasks/new.html.erb
<p>Enter the things you need to do here</p>
<%= render 'form' %>

<%= link_to 'Home', tasks_path %>